In [45]:
# Array Creation
# Task 1
import numpy as np

empty_array = np.empty((2, 2))
print(f"Empty 2x2 array:\n{empty_array}")

Empty 2x2 array:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [46]:
#Task 2
ones_array = np.ones((4, 2))
print(f"Ones 4x2 array:\n{ones_array}")

Ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [47]:
#Task 3
filled_array = np.full((3, 3), 7)
print(f"3x3 array filled with 7:\n{filled_array}")

3x3 array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [48]:
#task 4
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(sample_array)
print(f"Original array:\n{sample_array}")
print(f"Zeros like array:\n{zeros_like_array}")


Original array:
[[1 2 3]
 [4 5 6]]
Zeros like array:
[[0 0 0]
 [0 0 0]]


In [49]:
# Task 5
ones_like_array = np.ones_like(sample_array)
print(f"Ones like array:\n{ones_like_array}")

Ones like array:
[[1 1 1]
 [1 1 1]]


In [50]:
# Task 6
new_list = [1, 2, 3, 4]
numpy_from_list = np.array(new_list)
print(f"Original list: {new_list}")
print(f"Numpy array: {numpy_from_list}")


Original list: [1, 2, 3, 4]
Numpy array: [1 2 3 4]


In [51]:
#Array Manipulation
#Task 1
range_array = np.arange(10, 50)
print(f"Array: {range_array}")

Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [52]:
#Task2
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print(f"3x3 matrix:\n{matrix_3x3}")


3x3 matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [53]:
#Task3
identity_matrix = np.eye(3)
print(f"Identity matrix:\n{identity_matrix}")

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
#Task4
random_array = np.random.random(30)
mean_value = random_array.mean()
print(f"Random array (first 10 elements): {random_array[:10]}")
print(f"Mean of array: {mean_value:.4f}")

Random array (first 10 elements): [0.58731469 0.54580137 0.8435158  0.27274401 0.50290619 0.36955236
 0.93716169 0.39201254 0.67163857 0.2571048 ]
Mean of array: 0.4992


In [55]:
#Task5
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print(f"Minimum value: {min_value:.4f}")
print(f"Maximum value: {max_value:.4f}")

Minimum value: 0.0022
Maximum value: 0.9969


In [56]:
#Task6
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1  # 5th element (index 4)
print(f"Array: {zero_array_10}")


Array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [57]:
#task 7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"Original array: {arr}")
print(f"Reversed array: {reversed_arr}")


Original array: [1 2 0 0 4 0]
Reversed array: [0 4 0 0 2 1]


In [58]:
#Task 8
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(f"Border array:\n{border_array}")

Border array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
#Task 9
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print(f"Checkerboard pattern:\n{checkerboard}")

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [60]:
#Problem 3: Array Operation
#Task 1
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print(f"\nGiven arrays:")
print(f"x = \n{x}")
print(f"y = \n{y}")
print(f"v = {v}")
print(f"w = {w}")

print("\n--- Task 1: Add x and y ---")
add_result = x + y
print(f"x + y = \n{add_result}")


Given arrays:
x = 
[[1 2]
 [3 5]]
y = 
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

--- Task 1: Add x and y ---
x + y = 
[[ 6  8]
 [10 13]]


In [61]:
#Task 2
subtract_result = x - y
print(f"x - y = \n{subtract_result}")


x - y = 
[[-4 -4]
 [-4 -3]]


In [62]:
#Task3
multiply_result = x * 3
print(f"x * 3 = \n{multiply_result}")


x * 3 = 
[[ 3  6]
 [ 9 15]]


In [63]:
#Task4
square_result = x ** 2
print(f"x^2 = \n{square_result}")

x^2 = 
[[ 1  4]
 [ 9 25]]


In [64]:
#Task5
dot_v_w = np.dot(v, w)
print(f"v · w = {dot_v_w}")

v · w = 219


In [65]:
#Task6
concat_x_y_row = np.vstack((x, y))  # along rows
print(f"Concatenate x and y along rows:\n{concat_x_y_row}")

concat_v_w_col = np.vstack((v, w))  # along columns (as rows)
print(f"Concatenate v and w along column:\n{concat_v_w_col}")

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
[[ 9 10]
 [11 12]]


In [66]:
#Task7
try:
    concat_x_v = np.concatenate((x, v))
    print(f"Result: {concat_x_v}")
except ValueError as e:
    print(f"ERROR: {e}")
    print("Explanation: x has shape (2,2) and v has shape (2,).")
    print("They have incompatible shapes for direct concatenation.")
    print("We need to reshape v to match dimensions.")
    # Solution: reshape v
    v_reshaped = v.reshape(1, 2)
    concat_x_v = np.vstack((x, v_reshaped))
    print(f"After reshaping v to (1,2), concatenation works:\n{concat_x_v}")

ERROR: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x has shape (2,2) and v has shape (2,).
They have incompatible shapes for direct concatenation.
We need to reshape v to match dimensions.
After reshaping v to (1,2), concatenation works:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


In [67]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


In [68]:
# PROBLEM 4: MATRIX OPERATIONS
#Task 1
A_inv = np.linalg.inv(A)
identity_result = np.dot(A, A_inv)
print(f"A^-1 = \n{A_inv}")
print(f"A · A^-1 = \n{identity_result}")
print(f"Is it identity? {np.allclose(identity_result, np.eye(2))}")


A^-1 = 
[[-2.    1.  ]
 [ 1.75 -0.75]]
A · A^-1 = 
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is it identity? True


In [69]:
#Task2
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"AB = \n{AB}")
print(f"BA = \n{BA}")
print(f"Are they equal? {np.array_equal(AB, BA)}")
print("Conclusion: Matrix multiplication is NOT commutative!")


AB = 
[[23 13]
 [51 29]]
BA = 
[[36 44]
 [13 16]]
Are they equal? False
Conclusion: Matrix multiplication is NOT commutative!


In [70]:
#Task3
AB_transpose = AB.T
B_T_A_T = np.dot(B.T, A.T)
print(f"(AB)^T = \n{AB_transpose}")
print(f"B^T · A^T = \n{B_T_A_T}")
print(f"Are they equal? {np.array_equal(AB_transpose, B_T_A_T)}")

(AB)^T = 
[[23 51]
 [13 29]]
B^T · A^T = 
[[23 51]
 [13 29]]
Are they equal? True


In [71]:
#Task4
import numpy as np
print("System:")
print("2x - 3y + z = -1")
print("x - y + 2z = -3")
print("3x + y - z = 9")

# Coefficient matrix A
A_eq = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])

# Constants vector B
B_eq = np.array([-1, -3, 9])

print(f"\nCoefficient matrix A:\n{A_eq}")
print(f"Constants vector B: {B_eq}")

# Method 1: Using inverse
print("\n--- Method 1: Using inverse (A^-1 · B) ---")
A_eq_inv = np.linalg.inv(A_eq)
solution_inv = np.dot(A_eq_inv, B_eq)
print(f"Solution using inverse: x = {solution_inv[0]:.2f}, y = {solution_inv[1]:.2f}, z = {solution_inv[2]:.2f}")

# Method 2: Using np.linalg.solve
print("\n--- Method 2: Using np.linalg.solve ---")
solution_solve = np.linalg.solve(A_eq, B_eq)
print(f"Solution using solve: x = {solution_solve[0]:.2f}, y = {solution_solve[1]:.2f}, z = {solution_solve[2]:.2f}")

# Verification
print("\n--- Verification ---")
verification = np.dot(A_eq, solution_solve)
print(f"A · X = {verification}")
print(f"B = {B_eq}")
print(f"Correct? {np.allclose(verification, B_eq)}")

System:
2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9

Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants vector B: [-1 -3  9]

--- Method 1: Using inverse (A^-1 · B) ---
Solution using inverse: x = 2.00, y = 1.00, z = -2.00

--- Method 2: Using np.linalg.solve ---
Solution using solve: x = 2.00, y = 1.00, z = -2.00

--- Verification ---
A · X = [-1. -3.  9.]
B = [-1 -3  9]
Correct? True


In [44]:
import time
import numpy as np
size = 1_000_000
matrix_size = 1000

print(f"\nArray size: {size:,}")
print(f"Matrix size: {matrix_size}x{matrix_size}")

# 1. ELEMENT-WISE ADDITION
# Python lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
python_time = time.time() - start_time
print(f"Time taken: {python_time:.6f} seconds")

# NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
result_numpy = arr1 + arr2
numpy_time = time.time() - start_time
print(f"Time taken: {numpy_time:.6f} seconds")

speedup = python_time / numpy_time
print(f"\n✓ NumPy is {speedup:.2f}x FASTER than Python lists!")

# 2. ELEMENT-WISE MULTIPLICATION
# Python lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
python_time = time.time() - start_time
print(f"Time taken: {python_time:.6f} seconds")

# NumPy arrays
start_time = time.time()
result_numpy = arr1 * arr2
numpy_time = time.time() - start_time
print(f"Time taken: {numpy_time:.6f} seconds")

speedup = python_time / numpy_time
print(f"\n✓ NumPy is {speedup:.2f}x FASTER than Python lists!")

# 3. DOT PRODUCT
# Python lists
start_time = time.time()
result_list = sum([list1[i] * list2[i] for i in range(size)])
python_time = time.time() - start_time
print(f"Time taken: {python_time:.6f} seconds")

# NumPy arrays
start_time = time.time()
result_numpy = np.dot(arr1, arr2)
numpy_time = time.time() - start_time
print(f"Time taken: {numpy_time:.6f} seconds")

speedup = python_time / numpy_time
print(f"\n✓ NumPy is {speedup:.2f}x FASTER than Python lists!")


# 4. MATRIX MULTIPLICATION
# Python lists
matrix1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]

start_time = time.time()
# Matrix multiplication using nested loops
result_matrix = [[0 for _ in range(matrix_size)] for _ in range(matrix_size)]
for i in range(matrix_size):
    for j in range(matrix_size):
        for k in range(matrix_size):
            result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]
python_time = time.time() - start_time
print(f"Time taken: {python_time:.6f} seconds")

# NumPy arrays
np_matrix1 = np.arange(matrix_size * matrix_size).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size * matrix_size).reshape(matrix_size, matrix_size)

start_time = time.time()
result_np = np.dot(np_matrix1, np_matrix2)
numpy_time = time.time() - start_time
print(f"Time taken: {numpy_time:.6f} seconds")

speedup = python_time / numpy_time
print(f"\n✓ NumPy is {speedup:.2f}x FASTER than Python lists!")


Array size: 1,000,000
Matrix size: 1000x1000
Time taken: 0.120170 seconds
Time taken: 0.002157 seconds

✓ NumPy is 55.72x FASTER than Python lists!
Time taken: 0.130885 seconds
Time taken: 0.002803 seconds

✓ NumPy is 46.69x FASTER than Python lists!
Time taken: 0.169050 seconds
Time taken: 0.001948 seconds

✓ NumPy is 86.80x FASTER than Python lists!
Time taken: 401.747514 seconds
Time taken: 1.751477 seconds

✓ NumPy is 229.38x FASTER than Python lists!
